apiVersion: v1
kind: Service
metadata:
  name: vue-app-cluster-ip-service
  namespace: twitter-clone
spec:
  type: ClusterIP
  selector:
    component: vue-app
  ports:
    - port: 8081
      targetPort: 8081