version: "3.8"

services:
  mysqldb:
    platform: linux/amd64 # for macOS M1 chips
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./AccountService
    restart: on-failure
    container_name: app
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    # volumes:
    #   - .m2:/root/.m2
    stdin_open: true
    tty: true
  vueapp:
    depends_on:
      - mysqldb
    build: ./Pages/twitter-clone
    ports:
      - "8081:8081"
    volumes:
      - ./Pages/twitter-clone/src:/usr/src/app/src
      - ./Pages/twitter-clone/public:/usr/src/app/public
    container_name: vueapp

volumes:
  db: