apiVersion: v1
kind: Service
metadata:
  name: post-service-cluster-ip-service
  namespace: twitter-clone
spec:
  type: ClusterIP
  selector:
    component: post-service
  ports:
    - port: 8082
      targetPort: 8082