apiVersion: v1
kind: Service
metadata:
  name: account-service-cluster-ip-service
  namespace: twitter-clone
spec:
  type: ClusterIP
  selector:
    component: account-service
  ports:
    - port: 8080
      targetPort: 8080