apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vueapp
  template:
    metadata:
      labels:
        app: vueapp
    spec:
      containers:
        - name: vueapp
          image: microservices-for-myself_vueapp
          ports:
            - containerPort: 8081
